defaults: &defaults
  working_directory: ~/node-awscli
  docker:
    - image: circleci/node:8.10

version: 2
jobs:

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Image
          command: docker build .

  build_and_update:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            TAG=$(echo $CIRCLE_BRANCH | sed "s@/@_@g")
            docker build -t rhinogram/node-awscli:$TAG .
      - run:
          name: Login to Dockerhub
          command: docker login -u $USERNAME -p $PASSWORD
      - run:
          name: Update Docker Image
          command: docker push rhinogram/node-awscli:$TAG

workflows:
  version: 2

  updateDockerhub:
    jobs:
      - build_and_update:
          filters:
            branches:
              only:
                - '8.11'
                - '8.10'
