defaults: &defaults
  working_directory: ~/node-awscli
  docker:
    - image: circleci/node:6.11.2

version: 2
jobs:

  build_and_update:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: docker build -t rhinogram/node-awscli:$CIRCLE_BRANCH .
      - run:
          name: Login to Dockerhub
          command: docker login -u $USERNAME -p $PASSWORD
      - run:
          name: Update Docker Image
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker tag rhinogram/node-awscli:$CIRCLE_BRANCH rhinogram/node-awscli:latest
              docker push rhinogram/node-awscli:latest
            else
              docker push rhinogram/node-awscli:$CIRCLE_BRANCH
            fi

workflows:
  version: 2

  master:
    jobs:
      - build_and_update:
          filters:
            branches:
              only:
                - master
                - '8.9'
